/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Experiment */
        post: operations["stop_experiment_api_experiments__experiment_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Experiment */
        post: operations["pause_experiment_api_experiments__experiment_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Experiment */
        post: operations["resume_experiment_api_experiments__experiment_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Experiment Speed */
        post: operations["set_experiment_speed_api_experiments__experiment_id__speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Security Graph */
        get: operations["get_security_graph_api_experiments__experiment_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/analysis/attack-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attack Paths */
        get: operations["get_attack_paths_api_experiments__experiment_id__analysis_attack_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/analysis/blast-radius": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blast Radius */
        get: operations["get_blast_radius_api_experiments__experiment_id__analysis_blast_radius_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/analysis/critical-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Critical Nodes */
        get: operations["get_critical_nodes_api_experiments__experiment_id__analysis_critical_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/analysis/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Provenance
         * @description Backtraces node_id to its ultimate (patient zero) source via the
         *     compromised_by chain already carried by AgentNode -- reconstructs the
         *     causal attack trace (docs/PLAN.md §9's "causal replay/observability")
         *     without any new persistence, reusing app/graph/analysis.py::provenance
         *     (already implemented and tested in priority 1).
         */
        get: operations["get_provenance_api_experiments__experiment_id__analysis_provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_experiments__experiment_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/remediation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Remediation */
        get: operations["get_remediation_api_experiments__experiment_id__remediation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Detail */
        get: operations["get_experiment_detail_api_experiments__experiment_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Events */
        get: operations["get_experiment_events_api_experiments__experiment_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment Incidents */
        get: operations["get_experiment_incidents_api_experiments__experiment_id__incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Snapshot */
        get: operations["get_replay_snapshot_api_experiments__experiment_id__replay_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Graph */
        get: operations["get_replay_graph_api_experiments__experiment_id__replay_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/analysis/attack-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Attack Paths */
        get: operations["get_replay_attack_paths_api_experiments__experiment_id__replay_analysis_attack_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/analysis/blast-radius": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Blast Radius */
        get: operations["get_replay_blast_radius_api_experiments__experiment_id__replay_analysis_blast_radius_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/analysis/critical-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Critical Nodes */
        get: operations["get_replay_critical_nodes_api_experiments__experiment_id__replay_analysis_critical_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/analysis/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Provenance */
        get: operations["get_replay_provenance_api_experiments__experiment_id__replay_analysis_provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Metrics */
        get: operations["get_replay_metrics_api_experiments__experiment_id__replay_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/replay/remediation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Replay Remediation */
        get: operations["get_replay_remediation_api_experiments__experiment_id__replay_remediation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stream Frame Schema
         * @description Never called by any client. Its only purpose is to make StreamFrame's
         *     discriminated union appear in /openapi.json, which is what pulls the
         *     WebSocket payload shapes into the generated TypeScript types
         *     (SPEC §1 decision 4).
         */
        get: operations["get_stream_frame_schema_api_schema_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/otel-trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Otel Trace */
        get: operations["get_otel_trace_api_experiments__experiment_id__otel_trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttackPathsResponse */
        AttackPathsResponse: {
            /** Paths */
            paths: string[][];
        };
        /** BlastRadiusResponse */
        BlastRadiusResponse: {
            /** Compromised */
            compromised: string[];
            /** Reachable */
            reachable: string[];
            /** Fraction */
            fraction: number;
        };
        /** CriticalNodeView */
        CriticalNodeView: {
            /** Id */
            id: string;
            /** Betweenness */
            betweenness: number;
        };
        /** CriticalNodesResponse */
        CriticalNodesResponse: {
            /** Nodes */
            nodes: components["schemas"]["CriticalNodeView"][];
        };
        /**
         * EdgeType
         * @enum {string}
         */
        EdgeType: "communicates_with" | "delegates_to" | "trusts" | "can_access" | "uses_credential" | "monitors" | "quarantine_authority" | "updates_threat_memory";
        /** EdgeView */
        EdgeView: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * Event
         * @description Emitted, ordered, streamable.
         */
        Event: {
            /** Sim Tick */
            sim_tick: number;
            event_type: components["schemas"]["EventType"];
            /** Agent Id */
            agent_id?: string | null;
            /** Source Agent Id */
            source_agent_id?: string | null;
            /** Target Agent Id */
            target_agent_id?: string | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Metadata */
            metadata?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Seq */
            seq: number;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Wall Time
             * Format: date-time
             */
            wall_time: string;
        };
        /** EventFrame */
        EventFrame: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "event";
            event: components["schemas"]["Event"];
        };
        /** EventHistoryResponse */
        EventHistoryResponse: {
            /** Events */
            events: components["schemas"]["Event"][];
            /** Next Seq */
            next_seq: number | null;
        };
        /**
         * EventType
         * @enum {string}
         */
        EventType: "EXPERIMENT_STARTED" | "EXPERIMENT_STOPPED" | "AGENT_CREATED" | "AGENT_STARTED" | "AGENT_STOPPED" | "MESSAGE_SENT" | "MESSAGE_RECEIVED" | "MODEL_REQUESTED" | "MODEL_RESPONDED" | "TOOL_REQUESTED" | "TOOL_EXECUTED" | "TOOL_DENIED" | "MEMORY_READ" | "MEMORY_WRITE" | "CREDENTIAL_ACCESSED" | "CREDENTIAL_REVOKED" | "COMPROMISE_ATTEMPTED" | "COMPROMISE_SUCCEEDED" | "COMPROMISE_FAILED" | "ANOMALY_DETECTED" | "AGENT_QUARANTINED" | "AGENT_RELEASED" | "PERMISSION_CHANGED" | "INFERENCE_DISABLED" | "THREAT_SIGNATURE_PUBLISHED" | "THREAT_SIGNATURE_RECEIVED" | "AGENT_RECOVERED" | "POLICY_VIOLATION" | "ATTESTATION_ISSUED" | "ATTESTATION_VERIFIED";
        /** ExperimentConfig */
        ExperimentConfig: {
            /** Seed */
            seed: number;
            /**
             * Node Count
             * @default 60
             */
            node_count: number;
            /**
             * Edge Density
             * @default 2
             */
            edge_density: number;
            /**
             * Software Type Count
             * @default 3
             */
            software_type_count: number;
            /**
             * P Same
             * @default 0.15
             */
            p_same: number;
            /**
             * P Cross
             * @default 0.03
             */
            p_cross: number;
            /**
             * Max Ticks
             * @default 200
             */
            max_ticks: number;
            /**
             * Detector Sensitivity
             * @default 0.2
             */
            detector_sensitivity: number;
            /**
             * Defense Enabled
             * @default true
             */
            defense_enabled: boolean;
            /**
             * Initial Compromised
             * @default highest_degree
             * @enum {string}
             */
            initial_compromised: "highest_degree" | "random_node";
            /**
             * Real Agent Count
             * @default 0
             */
            real_agent_count: number;
            /**
             * Model Provider
             * @default mock
             * @enum {string}
             */
            model_provider: "mock" | "vllm";
            /**
             * Model Name
             * @default qwen-mock
             */
            model_name: string;
            /**
             * Model Max Tokens
             * @default 64
             */
            model_max_tokens: number;
            /**
             * Model Timeout S
             * @default 20
             */
            model_timeout_s: number;
            /**
             * Model Max Retries
             * @default 1
             */
            model_max_retries: number;
            /**
             * Model Max Concurrency
             * @default 4
             */
            model_max_concurrency: number;
            /**
             * Model Max Requests Per Experiment
             * @default 500
             */
            model_max_requests_per_experiment: number;
            /**
             * Tool Count
             * @default 0
             */
            tool_count: number;
            /**
             * Credential Count
             * @default 0
             */
            credential_count: number;
            /**
             * Resource Count
             * @default 0
             */
            resource_count: number;
            /**
             * Sentinel Count
             * @default 0
             */
            sentinel_count: number;
            /** Active Scenarios */
            active_scenarios?: string[];
            /**
             * Adaptive Detection Threshold
             * @default 0.3
             */
            adaptive_detection_threshold: number;
            /**
             * False Quarantine Rate
             * @default 0
             */
            false_quarantine_rate: number;
            /**
             * Sentinel Compromise Rate
             * @default 0
             */
            sentinel_compromise_rate: number;
            /**
             * Attestation Replay Rate
             * @default 0
             */
            attestation_replay_rate: number;
            /**
             * Byzantine Collusion Rate
             * @default 0
             */
            byzantine_collusion_rate: number;
        };
        /** ExperimentDetail */
        ExperimentDetail: {
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Seed */
            seed: number;
            config: components["schemas"]["ExperimentConfig"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Final Status */
            final_status: ("finished" | "stopped") | null;
            /** Final Sim Tick */
            final_sim_tick: number | null;
            /** Final Last Seq */
            final_last_seq: number | null;
            /** Is Complete */
            is_complete: boolean | null;
            /** App Version */
            app_version: string;
            /** Schema Version */
            schema_version: number;
            /** Completed At */
            completed_at: string | null;
        };
        /** ExperimentListItem */
        ExperimentListItem: {
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Seed */
            seed: number;
            config: components["schemas"]["ExperimentConfig"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Final Status */
            final_status: ("finished" | "stopped") | null;
            /** Final Sim Tick */
            final_sim_tick: number | null;
            /** Final Last Seq */
            final_last_seq: number | null;
            /** Is Complete */
            is_complete: boolean | null;
        };
        /** ExperimentListResponse */
        ExperimentListResponse: {
            /** Items */
            items: components["schemas"]["ExperimentListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ExperimentSummary */
        ExperimentSummary: {
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "paused" | "finished" | "stopped";
            /** Sim Tick */
            sim_tick: number;
            /** Last Seq */
            last_seq: number;
            config: components["schemas"]["ExperimentConfig"];
        };
        /** GraphEdgeView */
        GraphEdgeView: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            edge_type: components["schemas"]["EdgeType"];
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
        };
        /** GraphNodeView */
        GraphNodeView: {
            /** Id */
            id: string;
            node_type: components["schemas"]["NodeType"];
            security_state: components["schemas"]["SecurityState"];
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** MetricsResponse */
        MetricsResponse: {
            /** Compromise Fraction */
            compromise_fraction: number;
            /** Retained Utility */
            retained_utility: number;
            /** Blast Radius Fraction */
            blast_radius_fraction: number;
            /** Privileged Exposure */
            privileged_exposure: number;
            /** Security Plane Integrity */
            security_plane_integrity: number;
            /** Attack Success Rate */
            attack_success_rate: number;
            /** False Quarantine Rate */
            false_quarantine_rate: number;
            /** Detection Latency */
            detection_latency?: number | null;
            /** Containment Latency */
            containment_latency?: number | null;
        };
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "agent" | "tool" | "mcp_server" | "credential" | "resource" | "memory_store" | "sentinel" | "security_control";
        /** NodeView */
        NodeView: {
            /** Id */
            id: string;
            /** Software Type */
            software_type: string;
            security_state: components["schemas"]["SecurityState"];
            /** Compromised By */
            compromised_by?: string | null;
            /** Tick Compromised */
            tick_compromised?: number | null;
            /**
             * Agent Kind
             * @default simulated
             * @enum {string}
             */
            agent_kind: "simulated" | "real";
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /** Chain */
            chain: string[];
        };
        /** RecommendationView */
        RecommendationView: {
            /** Description */
            description: string;
            /** Config Diff */
            config_diff: {
                [key: string]: unknown;
            };
        };
        /** RemediationResponse */
        RemediationResponse: {
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationView"][];
        };
        /** SecurityGraphView */
        SecurityGraphView: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeView"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeView"][];
        };
        /**
         * SecurityState
         * @enum {string}
         */
        SecurityState: "healthy" | "suspicious" | "compromised" | "quarantined" | "recovered";
        /** SnapshotFrame */
        SnapshotFrame: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /** Last Seq */
            last_seq: number;
            /** Sim Tick */
            sim_tick: number;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "paused" | "finished" | "stopped";
            /** Nodes */
            nodes: components["schemas"]["NodeView"][];
            /** Edges */
            edges: components["schemas"]["EdgeView"][];
        };
        /** SpeedRequest */
        SpeedRequest: {
            /** Multiplier */
            multiplier: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_experiments_api_experiments_get: {
        parameters: {
            query?: {
                status?: ("finished" | "stopped" | "incomplete") | null;
                defense_enabled?: boolean | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_experiment_api_experiments__experiment_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_experiment_api_experiments__experiment_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_experiment_api_experiments__experiment_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_experiment_speed_api_experiments__experiment_id__speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_graph_api_experiments__experiment_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityGraphView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attack_paths_api_experiments__experiment_id__analysis_attack_paths_get: {
        parameters: {
            query: {
                source: string;
                target: string;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackPathsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blast_radius_api_experiments__experiment_id__analysis_blast_radius_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlastRadiusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_critical_nodes_api_experiments__experiment_id__analysis_critical_nodes_get: {
        parameters: {
            query?: {
                top_n?: number;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalNodesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provenance_api_experiments__experiment_id__analysis_provenance_get: {
        parameters: {
            query: {
                node_id: string;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_api_experiments__experiment_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_remediation_api_experiments__experiment_id__remediation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemediationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_detail_api_experiments__experiment_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_events_api_experiments__experiment_id__events_get: {
        parameters: {
            query?: {
                since_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_incidents_api_experiments__experiment_id__incidents_get: {
        parameters: {
            query?: {
                since_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_snapshot_api_experiments__experiment_id__replay_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotFrame"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_graph_api_experiments__experiment_id__replay_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityGraphView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_attack_paths_api_experiments__experiment_id__replay_analysis_attack_paths_get: {
        parameters: {
            query: {
                source: string;
                target: string;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttackPathsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_blast_radius_api_experiments__experiment_id__replay_analysis_blast_radius_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlastRadiusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_critical_nodes_api_experiments__experiment_id__replay_analysis_critical_nodes_get: {
        parameters: {
            query?: {
                top_n?: number;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalNodesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_provenance_api_experiments__experiment_id__replay_analysis_provenance_get: {
        parameters: {
            query: {
                node_id: string;
            };
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_metrics_api_experiments__experiment_id__replay_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_replay_remediation_api_experiments__experiment_id__replay_remediation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemediationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stream_frame_schema_api_schema_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotFrame"] | components["schemas"]["EventFrame"];
                };
            };
        };
    };
    get_otel_trace_api_experiments__experiment_id__otel_trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
